version: '3.8'

services:
  api1:
    build: .
    ports:
      - "8001:8000"
    networks:
      - blockchain_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Acceso a Docker en el host
      - blockchain_data:/app/data

  api2:
    build: .
    ports:
      - "8002:8000"
    networks:
      - blockchain_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - blockchain_data:/app/data

  api3:
    build: .
    ports:
      - "8003:8000"
    networks:
      - blockchain_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - blockchain_data:/app/data
  
  api4:
    build: .
    ports:
      - "8004:8000"
    networks:
      - blockchain_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - blockchain_data:/app/data

networks:
  blockchain_net:
    driver: bridge

volumes:
  blockchain_data:
